# Generated by Django 4.2.16 on 2024-11-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="photo",
            field=models.ImageField(upload_to="gallery/%Y/%m/%d/"),
        ),
    ]
