# Generated by Django 4.2 on 2024-05-23 04:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_usersession"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
